export const ABLocators = {
  firstBahar: '[data-name="bet-first-bahar"]',
  firstAndar: '[data-name="bet-first-andar"]',
  sideAndar: '[data-name="side-bet-andar"]',
  sideBahar: '[data-name="side-bet-bahar"]',
  secondAndar: '[data-name="bet-second-andar"]',
  secondBahar: '[data-name="bet-second-bahar"]',
  // blinkAnimationAndarVert: '#a-betSpotSVG-vert > feFlood',
  // blinkAnimationBaharVert: '#h-betSpotSVG-vert > feFlood',
  // blinkAnimationAndarHoriz: '[data-name="bet-first-andar"]',
  // blinkAnimationBaharHoriz: '[data-name="bet-second-bahar"]',
};

export const BACLocators = {
  player: '[data-name="main-bet player"]',
  banker: '[data-name="main-bet banker"]',
  tie: '[data-name="main-bet tie"]',
  superSix: '[data-name="side-bet superSix"]',
  dragon: '[data-name="side-bet dragon"]',
  tiger: '[data-name="side-bet tiger"]',
  playerPair: '[data-name="side-bet playerPair"]',
  bankerPair: '[data-name="side-bet bankerPair"]',
  noCommision: '#nocommission',
};

export const BJLocators = {
  mainBetspot: '[data-name="main-bet"]',
  mainBetspotChip: '[data-testid="main-bet-chip"]',
  betBehind: '[data-name="bet-behind"]',
  betBehindBetspotChip: '[data-testid="bet-behind-chip"]',
  perfectPairs: '[data-name="side-bet perfectPair"]',
  perfectPairBetspotChip: '[data-testid="side-bet-chip perfectPair"]',
  twentyonePlusThree: '[data-name="side-bet twentyOnePlusThree"]',
  twentyonePlusThreeBetspotChip: '[data-testid="side-bet-chip twentyOnePlusThree"]',
  dealNow: '[data-name="deal-now-button"]',
  seat1: '#seat-1',
  seat2: '#seat-2',
  seat3: '#seat-3',
  seat4: '#seat-4',
  seat5: '#seat-5',
  seat6: '#seat-6',
  seat7: '#seat-7',
  leaveSeatAll: '#leave-seat',
  seatMainChipContainer: '[data-testid="chip-container"]',
  seatMainChip: '[data-testid="chip"]',
  freeSeat: '[data-name="status-free"]',
  busySeat: '[data-name="status-busy"]',
  virtualPanelDealerText: '#dealer',
  virtualPanelPlayerText: '#player',

  decisionHitBtn: '[data-testid="decision-hit"]',
  decisionStandBtn: '[data-testid="decision-stand"]',
  decisionSplitBtn: '[data-testid="decision-split"]',
  decisionDoubleDownBtn: '[data-testid="decision-doubleDown"]',

  insuranceText: '[data-testid="insuranceText"]',
  insuranceYesBtn: '.icon-insuranceYes',
  insuranceYesText: '[data-testid="decisionYesText"]',
  insuranceNoBtn: '[data-testid="decisionNo"]',
  insuranceNoText: '[data-testid="decisionNoText"]',
  insuranceIcon: '[data-testid="iconInsurance"]',

  evenMoneyText: '[data-testid="evenMoneyText"]',
  evenMoneyYesBtn: '.icon-evenMoneyYes',
  evenMoneyYesText: '[data-testid="decisionYesText"]',
  evenMoneyNoBtn: '[data-testid="decisionNo"]',
  evenMoneyNoText: '[data-testid="decisionNoText"]',
  evenMoneyIcon: '[data-testid="iconEvenMoney"]',

  dealerCardsSum: '[data-testid="dealerCardsSum"]',
  playerCardsSum: '[data-testid="playerCardsSum"]',
};

export const DTLocators = {
  dragon: '[data-testid="main-bet dragon"]',
  dragonChip: '[data-testid="main-bet-chip dragon"]',
  dragonText: '[data-testid="dragonText"]',
  dragonBetspotBackground: '[data-testid="dragonBackground"]',
  dragonIcon: '.icon.icon-dragonSymbol svg',
  tiger: '[data-testid="main-bet tiger"]',
  tigerChip: '[data-testid="main-bet-chip tiger"]',
  tigerText: '[data-testid="tigerText"]',
  tigerBetspotBackground: '[data-testid="tigerBackground"]',
  tigerIcon: '.icon.icon-dragonSymbol svg',
  tie: '[data-testid="main-bet tie"]',
  tieChip: '[data-testid="main-bet-chip tie"]',
  tieText: '[data-testid="TieText"]',
  tieBetspotBackground: '[data-testid="tieBackground"]',
  tieIcon: '.icon.icon-tieSymbol',
  dragonSmall: '[data-testid="side-bet dragonSmall"]',
  dragonSmallChip: '[data-testid="side-bet-chip dragonSmall"]',
  dragonBig: '[data-testid="side-bet dragonBig"]',
  dragonBigChip: '[data-testid="side-bet-chip dragonBig"]',
  dragonHearts: '[data-testid="side-bet dragonHearts"]',
  dragonHeartsChip: '[data-testid="side-bet-chip dragonHearts"]',
  dragonDiamonds: '[data-testid="side-bet dragonDiamond"]',
  dragonDiamondsChip: '[data-testid="side-bet-chip dragonDiamond"]',
  dragonClubs: '[data-testid="side-bet dragonClubs"]',
  dragonClubsChip: '[data-testid="side-bet-chip dragonClubs"]',
  dragonSpades: '[data-testid="side-bet dragonSpades"]',
  dragonSpadesChip: '[data-testid="side-bet-chip dragonSpades"]',
  tigerSmall: '[data-testid="side-bet tigerSmall"]',
  tigerSmallChip: '[data-testid="side-bet-chip tigerSmall"]',
  tigerBig: '[data-testid="side-bet tigerBig"]',
  tigerBigChip: '[data-testid="side-bet-chip tigerBig"]',
  tigerHearts: '[data-testid="side-bet tigerHearts"]',
  tigerHeartsChip: '[data-testid="side-bet-chip tigerHearts"]',
  tigerDiamonds: '[data-testid="side-bet tigerDiamond"]',
  tigerDiamondsChip: '[data-testid="side-bet-chip tigerDiamond"]',
  tigerClubs: '[data-testid="side-bet tigerClubs"]',
  tigerClubsChip: '[data-testid="side-bet-chip tigerClubs"]',
  tigerSpades: '[data-testid="side-bet tigerSpades"]',
  tigerSpadesChip: '[data-testid="side-bet-chip tigerSpades"]',

  tigerTotalChips: '[data-testid="bettingPercentageTiger"]',
  dragonTotalChips: '[data-testid="bettingPercentageDragon"]',
  tieTotalChips: '[data-testid="bettingPercentageTie"]',

  roadMap: '[data-testid="roadmap"]',
  roadMapItems: '[data-testid="roadmap"] svg g',
  predictionRoad: '[data-testid="predictionRoad"]',
  roadmapFirstItem: '[data-testid="roadmapFirstItem"]',
  roadmapFirstItemColor: '[data-testid="roadmapFirstItemColor"]',

  dragonVirtualCard: '[data-testid="dragonVirtualCard"]',
  tigerVirtualCard: '[data-testid="tigerVirtualCard"]',

  dragonBackgroundColor: '[data-testid="dragonBackground"]',
  tigerBackgroundColor: '[data-testid="tigerBackground"]',
  tieBackgroundColor: '[data-testid="TieBackground"]',

  heartsIcons: '.icon.icon-hearts',
  diamondIcons: '.icon.icon-diamond',
  clubsIcons: '.icon.icon-clubs',
  spadesIcons: '.icon.icon-spades',

  tigerWinBackgroundColor: '[data-testid="tigerWinsBg"]',
  dragonWinBackgroundColor: '[data-testid="dragonWinsBg"]',
  tieWinBackgroundColor: '[data-testid="tieWinsBg"]',
};

export const ROLocators = {
  racetrack: {
    racetrackBtn: '[data-testid="racetrackBtn"]',
    racetrackBettingArea: '[data-testid="racetrack"]',
    racetrackBettingAreaSvg: '[data-testid="racetrackSVG"]',
    zero: '[data-testid="bet-0"]',
    zeroChip: '[data-testid="racetrack-0-chip"]',
    one: '[data-testid="bet-1"]',
    oneChip: '[data-testid="racetrack-1-chip"]',
    two: '[data-testid="bet-2"]',
    twoChip: '[data-testid="racetrack-2-chip"]',
    three: '[data-testid="bet-3"]',
    threeChip: '[data-testid="racetrack-3-chip"]',
    four: '[data-testid="bet-4"]',
    fourChip: '[data-testid="racetrack-4-chip"]',
    five: '[data-testid="bet-5"]',
    fiveChip: '[data-testid="racetrack-5-chip"]',
    six: '[data-testid="bet-6"]',
    sixChip: '[data-testid="racetrack-6-chip"]',
    seven: '[data-testid="bet-7"]',
    sevenChip: '[data-testid="racetrack-7-chip"]',
    eight: '[data-testid="bet-8"]',
    eightChip: '[data-testid="racetrack-8-chip"]',
    nine: '[data-testid="bet-9"]',
    nineChip: '[data-testid="racetrack-9-chip"]',
    ten: '[data-testid="bet-10"]',
    tenChip: '[data-testid="racetrack-10-chip"]',
    eleven: '[data-testid="bet-11"]',
    elevenChip: '[data-testid="racetrack-11-chip"]',
    twelve: '[data-testid="bet-12"]',
    twelveChip: '[data-testid="racetrack-12-chip"]',
    thirteen: '[data-testid="bet-13"]',
    thirteenChip: '[data-testid="racetrack-13-chip"]',
    fourteen: '[data-testid="bet-14"]',
    fourteenChip: '[data-testid="racetrack-14-chip"]',
    fifteen: '[data-testid="bet-15"]',
    fifteenChip: '[data-testid="racetrack-15-chip"]',
    sixteen: '[data-testid="bet-16"]',
    sixteenChip: '[data-testid="racetrack-16-chip"]',
    seventeen: '[data-testid="bet-17"]',
    seventeenChip: '[data-testid="racetrack-17-chip"]',
    eighteen: '[data-testid="bet-18"]',
    eighteenChip: '[data-testid="racetrack-18-chip"]',
    nineteen: '[data-testid="bet-19"]',
    nineteenChip: '[data-testid="racetrack-19-chip"]',
    twenty: '[data-testid="bet-20"]',
    twentyChip: '[data-testid="racetrack-20-chip"]',
    twentyone: '[data-testid="bet-21"]',
    twentyoneChip: '[data-testid="racetrack-21-chip"]',
    twentytwo: '[data-testid="bet-22"]',
    twentytwoChip: '[data-testid="racetrack-22-chip"]',
    twentythree: '[data-testid="bet-23"]',
    twentythreeChip: '[data-testid="racetrack-23-chip"]',
    twentyfour: '[data-testid="bet-24"]',
    twentyfourChip: '[data-testid="racetrack-24-chip"]',
    twentyfive: '[data-testid="bet-25"]',
    twentyfiveChip: '[data-testid="racetrack-25-chip"]',
    twentysix: '[data-testid="bet-26"]',
    twentysixChip: '[data-testid="racetrack-26-chip"]',
    twentyseven: '[data-testid="bet-27"]',
    twentysevenChip: '[data-testid="racetrack-27-chip"]',
    twentyeight: '[data-testid="bet-28"]',
    twentyeightChip: '[data-testid="racetrack-28-chip"]',
    twentynine: '[data-testid="bet-29"]',
    twentynineChip: '[data-testid="racetrack-29-chip"]',
    thirty: '[data-testid="bet-30"]',
    thirtyChip: '[data-testid="racetrack-30-chip"]',
    thirtyone: '[data-testid="bet-31"]',
    thirtyoneChip: '[data-testid="racetrack-31-chip"]',
    thirtytwo: '[data-testid="bet-32"]',
    thirtytwoChip: '[data-testid="racetrack-32-chip"]',
    thirtythree: '[data-testid="bet-33"]',
    thirtythreeChip: '[data-testid="racetrack-33-chip"]',
    thirtyfour: '[data-testid="bet-34"]',
    thirtyfourChip: '[data-testid="racetrack-34-chip"]',
    thirtyfive: '[data-testid="bet-35"]',
    thirtyfiveChip: '[data-testid="racetrack-35-chip"]',
    thirtysix: '[data-testid="bet-36"]',
    thirtysixChip: '[data-testid="racetrack-36-chip"]',

    combinedBetspots:
    {
      tier: '[data-testid="racetrackTier"]',
      tierChip: '[data-testid="racetrack-Tier-chip"]',
      orphelins: '[data-testid="racetrackOrphelins"]',
      orphelinsChip: '[data-testid="racetrack-Orphelins-chip"]',
      voisinsDuZero: '[data-testid="racetrackVoisins ,du zero"]',
      voisinsDuZeroChip: '[data-testid="racetrack-Voisins-chip"]',
    },
  },

  sideBets: {
    left: ' [data-name="side-bet left"]',
    leftChip: ' [data-testid="side-bet-chip left"]',
    bottom: ' [data-name="side-bet bottom"]',
    bottomChip: ' [data-testid="side-bet-chip bottom"]',
    corner: ' [data-name="side-bet corner"]',
    cornerChip: ' div[data-testid="side-bet-chip corner"]',
  },

  inside: {
    zero: {
      betspot: '[data-name="main-bet 0"]',
      chip: '[data-testid="main-bet-chip 0"]',
      background: '[data-testid="zeroBackgroundColor"]',
      multiplier: '[data-testid="multiplier0"]',
      winHighlight: '[data-testid="zeroWinningHighlight"]',
      fontColor: '[data-testid="zeroFontColor"]',
    },
    one: {
      betspot: '[data-name="main-bet 1"]',
      chip: '[data-testid="main-bet-chip 1"]',
      multiplier: '[data-testid="multiplier1"]',
      sideBets: {
        left: {
          betspot: '  [data-name="side-bet left"]',
          chip: '[data-testid="side-bet-chip left 37 "]',
        },
        bottom: {
          betspot: ' [data-name="side-bet bottom"]',
          chip: '[data-testid="side-bet-chip bottom 99 "]',
        },
        corner: {
          betspot: ' [data-name="side-bet corner"]',
          chip: '[data-testid="side-bet-chip corner 111 "]',
        }
      }
    },
    two: {
      betspot: '[data-name="main-bet 2"]',
      chip: '[data-testid="main-bet-chip 2"]',
      multiplier: '[data-testid="multiplier2"]',
    },
    three: {
      betspot: '[data-name="main-bet 3"]',
      chip: '[data-testid="main-bet-chip 3"]',
      multiplier: '[data-testid="multiplier3"]',
    },
    four: {
      betspot: '[data-name="main-bet 4"]',
      chip: '[data-testid="main-bet-chip 4"]',
      multiplier: '[data-testid="multiplier4"]',
    },
    five: {
      betspot: '[data-name="main-bet 5"]',
      chip: '[data-testid="main-bet-chip 5"]',
      multiplier: '[data-testid="multiplier5"]',
    },
    six: {
      betspot: '[data-name="main-bet 6"]',
      chip: '[data-testid="main-bet-chip 6"]',
      multiplier: '[data-testid="multiplier6"]',
    },
    seven: {
      betspot: '[data-name="main-bet 7"]',
      chip: '[data-testid="main-bet-chip 7"]',
      multiplier: '[data-testid="multiplier7"]',
    },
    eight: {
      betspot: '[data-name="main-bet 8"]',
      chip: '[data-testid="main-bet-chip 8"]',
      multiplier: '[data-testid="multiplier8"]',
    },
    nine: {
      betspot: '[data-name="main-bet 9"]',
      chip: '[data-testid="main-bet-chip 9"]',
      multiplier: '[data-testid="multiplier9"]',
    },
    ten: {
      betspot: '[data-name="main-bet 10"]',
      chip: '[data-testid="main-bet-chip 10"]',
      multiplier: '[data-testid="multiplier10"]',
    },
    eleven: {
      betspot: '[data-name="main-bet 11"]',
      chip: '[data-testid="main-bet-chip 11"]',
      multiplier: '[data-testid="multiplier11"]',
    },
    twelve: {
      betspot: '[data-name="main-bet 12"]',
      chip: '[data-testid="main-bet-chip 12"]',
      multiplier: '[data-testid="multiplier12"]',
    },
    thirteen: {
      betspot: '[data-name="main-bet 13"]',
      chip: '[data-testid="main-bet-chip 13"]',
      multiplier: '[data-testid="multiplier13"]',
    },
    fourteen: {
      betspot: '[data-name="main-bet 14"]',
      chip: '[data-testid="main-bet-chip 14"]',
      multiplier: '[data-testid="multiplier14"]',
    },
    fifteen: {
      betspot: '[data-name="main-bet 15"]',
      chip: '[data-testid="main-bet-chip 15"]',
      multiplier: '[data-testid="multiplier15"]',
    },
    sixteen: {
      betspot: '[data-name="main-bet 16"]',
      chip: '[data-testid="main-bet-chip 16"]',
      multiplier: '[data-testid="multiplier16"]',
    },
    seventeen: {
      betspot: '[data-name="main-bet 17"]',
      chip: '[data-testid="main-bet-chip 17"]',
      multiplier: '[data-testid="multiplier17"]',
    },
    eighteen: {
      betspot: '[data-name="main-bet 18"]',
      chip: '[data-testid="main-bet-chip 18"]',
      multiplier: '[data-testid="multiplier18"]',
    },
    nineteen: {
      betspot: '[data-name="main-bet 19"]',
      chip: '[data-testid="main-bet-chip 19"]',
      multiplier: '[data-testid="multiplier19"]',
    },
    twenty: {
      betspot: '[data-name="main-bet 20"]',
      chip: '[data-testid="main-bet-chip 20"]',
      multiplier: '[data-testid="multiplier20"]',
    },
    twentyone: {
      betspot: '[data-name="main-bet 21"]',
      chip: '[data-testid="main-bet-chip 21"]',
      multiplier: '[data-testid="multiplier21"]',
    },
    twentytwo: {
      betspot: '[data-name="main-bet 22"]',
      chip: '[data-testid="main-bet-chip 22"]',
      multiplier: '[data-testid="multiplier22"]',
    },
    twentythree: {
      betspot: '[data-name="main-bet 23"]',
      chip: '[data-testid="main-bet-chip 23"]',
      multiplier: '[data-testid="multiplier23"]',
    },
    twentyfour: {
      betspot: '[data-name="main-bet 24"]',
      chip: '[data-testid="main-bet-chip 24"]',
      multiplier: '[data-testid="multiplier24"]',
    },
    twentyfive: {
      betspot: '[data-name="main-bet 25"]',
      chip: '[data-testid="main-bet-chip 25"]',
      multiplier: '[data-testid="multiplier25"]',
    },
    twentysix: {
      betspot: '[data-name="main-bet 26"]',
      chip: '[data-testid="main-bet-chip 26"]',
      multiplier: '[data-testid="multiplier26"]',
    },
    twentyseven: {
      betspot: '[data-name="main-bet 27"]',
      chip: '[data-testid="main-bet-chip 27"]',
      multiplier: '[data-testid="multiplier27"]',
    },
    twentyeight: {
      betspot: '[data-name="main-bet 28"]',
      chip: '[data-testid="main-bet-chip 28"]',
      multiplier: '[data-testid="multiplier28"]',
    },
    twentynine: {
      betspot: '[data-name="main-bet 29"]',
      chip: '[data-testid="main-bet-chip 29"]',
      multiplier: '[data-testid="multiplier29"]',
    },
    thirty: {
      betspot: '[data-name="main-bet 30"]',
      chip: '[data-testid="main-bet-chip 30"]',
      multiplier: '[data-testid="multiplier30"]',
    },
    thirtyone: {
      betspot: '[data-name="main-bet 31"]',
      chip: '[data-testid="main-bet-chip 31"]',
      multiplier: '[data-testid="multiplier31"]',
    },
    thirtytwo: {
      betspot: '[data-name="main-bet 32"]',
      chip: '[data-testid="main-bet-chip 32"]',
      multiplier: '[data-testid="multiplier32"]',
    },
    thirtythree: {
      betspot: '[data-name="main-bet 33"]',
      chip: '[data-testid="main-bet-chip 33"]',
      multiplier: '[data-testid="multiplier33"]',
    },
    thirtyfour: {
      betspot: '[data-name="main-bet 34"]',
      chip: '[data-testid="main-bet-chip 34"]',
      multiplier: '[data-testid="multiplier34"]',
    },
    thirtyfive: {
      betspot: '[data-name="main-bet 35"]',
      chip: '[data-testid="main-bet-chip 35"]',
      multiplier: '[data-testid="multiplier35"]',
    },
    thirtysix: {
      betspot: '[data-name="main-bet 36"]',
      chip: '[data-testid="main-bet-chip 36"]',
      multiplier: '[data-testid="multiplier36"]',
    }
  },


  outside: {
    dozenFirst: '[data-testid="side-bet-chip-cell 1st 12"]',
    dozenFirstChip: '[data-testid="side-bet-chip 1st 12 145 "]',
    dozenSecond: '[data-testid="side-bet-chip-cell 2nd 12"]',
    dozenSecondChip: '[data-testid="side-bet-chip 2nd 12 146 "]',
    dozenThird: '[data-testid="side-bet-chip-cell 3rd 12"]',
    dozenThirdChip: '[data-testid="side-bet-chip 3rd 12 147 "]',
    oneto18: '[data-testid="side-bet-chip-cell 1-18"]',
    oneto18Chip: '[data-testid="side-bet-chip 1-18"]',
    nineteento36: '[data-testid="side-bet-chip-cell 19-36"]',
    nineteento36Chip: '[data-testid="side-bet-chip 19-36"]',
    even: '[data-testid="side-bet-chip-cell EVEN"]',
    evenChip: '[data-testid="side-bet-chip EVEN"]',
    odd: '[data-testid="side-bet-chip-cell ODD"]',
    oddChip: '[data-testid="side-bet-chip ODD"]',
    red: '[data-testid="side-bet-chip-cell red"]',
    redChip: '[data-testid="side-bet-chip red"]',
    redDiamond: '[data-testid="redDiamondColor"]',
    black: '[data-testid="side-bet-chip-cell black"]',
    blackChip: '[data-testid="side-bet-chip black"]',
    blackDiamond: '[data-testid="blackDiamondColor"]',
    blue: '[data-name="side-bet #009BD4"]',
    bblueChip: '[data-testid="side-bet-chip blue"]',
    blueDiamond: '[data-testid="blueDiamondColor"]',
    columnThird: '[data-name="side-bet 2 to 1 150 "]',
    columnThirdChip: '[data-testid="side-bet-chip 2 to 1 150 "]',
    columnSecond: '[data-name="side-bet 2 to 1 149 "]',
    columnSecondChip: '[data-testid="side-bet-chip 2 to 1 149 "]',
    columnFirst: '[data-name="side-bet 2 to 1 148 "]',
    columnFirstChip: '[data-testid="side-bet-chip 2 to 1 148 "]',
  },

  chipSpecific: {
    chipColor: '[data-testid="chipColor"]',
    chipText: '[data-testid="chipText"]',
  },

  mainBettingArea: '#table-inner',

  bettingTableOnly: '[data-testid="betingTable"]',
  winNumberAnimation: '[data-testid="winningAnimationWithNumbers"]',

  headerWinningNumber: '[data-testid="winningNumber"]',
  dolly: '[data-testid="dolly"]',
  menuCloseBtn: '[data-testid="menuCloseBtn"]',

  lastWin: {
    lastWinbar: '[data-testid="lastWinbar"]',
    lastWinNumber: '[data-testid="lastWinbarNumber"]',
    lastWinMultiplier: '[data-testid="lastWinNumberMultiplier"]',
    winBarNumber1: '[data-testid="otherWinbarNumber 1"]',
    lastWinMultiplier1: '[data-testid="lastWinNumberMultiplier1"]',
    winBarNumber2: '[data-testid="otherWinbarNumber 2"]',
    lastWinMultiplier2: '[data-testid="lastWinNumberMultiplier2"]',
    winBarNumber3: '[data-testid="otherWinbarNumber 3"]',
    lastWinMultiplier3: '[data-testid="lastWinNumberMultiplier3"]',
    winBarNumber4: '[data-testid="otherWinbarNumber 4"]',
    lastWinMultiplier4: '[data-testid="lastWinNumberMultiplier4"]',
    winBarNumber5: '[data-testid="otherWinbarNumber 5"]',
    lastWinMultiplier5: '[data-testid="lastWinNumberMultiplier5"]',
    winBarNumber6: '[data-testid="otherWinbarNumber 6"]',
    lastWinMultiplier6: '[data-testid="lastWinNumberMultiplier6"]',
    winBarNumber7: '[data-testid="otherWinbarNumber 7"]',
    lastWinMultiplier7: '[data-testid="lastWinNumberMultiplier7"]',
    winBarNumber8: '[data-testid="otherWinbarNumber 8"]',
    lastWinMultiplier8: '[data-testid="lastWinNumberMultiplier8"]',
    winBarNumber9: '[data-testid="otherWinbarNumber 9"]',
    lastWinMultiplier9: '[data-testid="lastWinNumberMultiplier9"]',
    winBarumber10: '[data-testid="otherWinbarNumber 10"]',
    lastWinMultiplier10: '[data-testid="lastWinNumberMultiplier10"]',
    winBarNumber11: '[data-testid="otherWinbarNumber 11"]',
    lastWinMultiplier11: '[data-testid="lastWinNumberMultiplier11"]',
    winBarNumber12: '[data-testid="otherWinbarNumber 12"]',
    lastWinMultiplier12: '[data-testid="lastWinNumberMultiplier12"]',
    winBarNumber13: '[data-testid="otherWinbarNumber 13"]',
    lastWinMultiplier13: '[data-testid="lastWinNumberMultiplier13"]',
  },

  statistics: {
    statisticsBtn: '[data-testid="statisticsBtn"]',
    statisticsTab: '[data-testid="statisticsTab"]',
    statisticsTitle: '[data-testid="statisticsTitle"]',
    statisticsTitleIcon: '[data-testid="statisticsTitleIcon"]',
    statisticsTable1: '[data-testid="statisticsTable1"]',
    statisticsTableRacetrackFirstColumn: '[data-testid="statisticsTable1Column1"]',
    statisticsTableRacetrackSecondColumn: '[data-testid="statisticsTable1Column2"]',
    statisticsTableRacetrackThirdColumn: '[data-testid="statisticsTable1Column3"]',
    statisticsTableRacetrackFourthColumn: '[data-testid="statisticsTable1Column4"]',
    statisticsTableColors: '[data-testid="statisticsTable2"]',
    statisticsTableColorsFirstColumn: '[data-testid="statisticsTable2Column1"]',
    statisticsTableColorsSecondColumn: '[data-testid="statisticsTable2Column2"]',
    statisticsTableColorsThirdColumn: '[data-testid="statisticsTable2Column3"]',
    statisticsTableEvenOdd: '[data-testid="statisticsTable3"]',
    statisticsTableEvenOddFirstColumn: '[data-testid="statisticsTable3Column1"]',
    statisticsTableEvenOddSecondColumn: '[data-testid="statisticsTable3Column2"]',
    statisticsTableEvenOddThirdColumn: '[data-testid="statisticsTable3Column3"]',
    statisticsTableHotNumbers: '[data-testid="statisticsTableHotNumbers"]',
    statisticsTableColdNumbers: '[data-testid="statisticsTableColdNumbers"]',
    statisticsSlider: '[data-testid="statisticsSlider"]',
    statisticsSlider100Rounds: '[data-testid="statisticsSlider100Rounds"]',
    statisticsSlider100RoundsText: '[data-testid="statisticsSlider100RoundsText"]',
    statisticsSlider100RoundsCircle: '[data-testid="statisticsSlider100RoundsCircle"]',
    statisticsSlider200Rounds: '[data-testid="statisticsSlider200Rounds"]',
    statisticsSlider200RoundsText: '[data-testid="statisticsSlider200RoundsText"]',
    statisticsSlider300Rounds: '[data-testid="statisticsSlider300Rounds"]',
    statisticsSlider300RoundsText: '[data-testid="statisticsSlider300RoundsText"]',
    statisticsSlider400Rounds: '[data-testid="statisticsSlider400Rounds"]',
    statisticsSlider400RoundsText: '[data-testid="statisticsSlider400RoundsText"]',
    statisticsSlider500Rounds: '[data-testid="statisticsSlider500Rounds"]',
    statisticsSlider500RoundsText: '[data-testid="statisticsSlider500RoundsText"]',
    statisticsLast100Rounds: '[data-testid="statisticsLastRounds"]',
    statisticsImage: '[data-testid="statisticsImage"]',

  },

  favoriteBets: {
    //generic
    favoritBetsBtn: '[data-testid="favoriteBetsBtn"]',
    favoritBetsTab: '[data-testid="favoritebetsTab"]',
    tabTitle: '[data-testid="favoritebetsTitle"]',
    tabIcon: '[data-testid="favoritebetsTitleIcon"]',
    // welcome screen
    tabImageNoPlacedBets: '[data-testid="nosavedbetsicon"]',
    tabTextNoPlacedBets: '[data-testid="nosavedbetstext"]',
    // save bets section
    saveLastBetsField1: '[data-testid="favoriteBetsSaveLastbet1"]',
    saveLastBetsField2: '[data-testid="favoriteBetsSaveLastbet2"]',
    saveLastBetsField3: '[data-testid="favoriteBetsSaveLastbet3"]',
    saveLastBetsField4: '[data-testid="favoriteBetsSaveLastbet4"]',
    star1: '[data-testid="favoriteBetsSaveLastbet1Star"]',
    field1WithSavedBets: '[data-testid="favoritbetstotalamountfieldText1"]',

    //repeat bets section
    autoConfirmText: '[data-testid="AutoConfirmText"]',
    switchToggle: '[data-testid="autoconfirmslider"]',
    roundSlider: '[data-testid="favoritebetsroundsslider"]',
    textBelowRoundsSlider: '[data-testid="favoritbetsroundsselected"]',
    playButton: '[data-testid="playbtn"]',
  },

  luckyNumbers: {
    luckyNumbersContainer: '[data-testid="LuckyNumberContainer"]',

    luckyNumberBox0: '[data-testid="LuckyNumberBox 0"]',
    luckyNumberBoxSvg0: '[data-testid="luckyNumberBoxSvg 0"]',
    luckyNumberBox0Chip: '[data-testid="chipOnLuckyNumberBox 0"]',
    luckyNumberBox0Text: '[data-testid="TextOnLuckyNumberBox 0"]',

    luckyNumberBox1: '[data-testid="LuckyNumberBox 1"]',
    luckyNumberBoxSvg1: '[data-testid="luckyNumberBoxSvg 1"]',
    luckyNumberBox1Chip: '[data-testid="chipOnLuckyNumberBox 1"]',
    luckyNumberBox1Text: '[data-testid="TextOnLuckyNumberBox 1"]',

    luckyNumberBox2: '[data-testid="LuckyNumberBox 2"]',
    luckyNumberBoxSvg2: '[data-testid="luckyNumberBoxSvg 2"]',
    luckyNumberBox2Chip: '[data-testid="chipOnLuckyNumberBox 2"]',
    luckyNumberBox2Text: '[data-testid="TextOnLuckyNumberBox 2"]',

    luckyNumberBox3: '[data-testid="LuckyNumberBox 3"]',
    luckyNumberBoxSvg3: '[data-testid="luckyNumberBoxSvg 3"]',
    luckyNumberBox3Chip: '[data-testid="chipOnLuckyNumberBox 3"]',
    luckyNumberBox3Text: '[data-testid="TextOnLuckyNumberBox 3"]',

    luckyNumberBox4: '[data-testid="LuckyNumberBox 4"]',
    luckyNumberBoxSvg4: '[data-testid="luckyNumberBoxSvg 4"]',
    luckyNumberBox4Chip: '[data-testid="chipOnLuckyNumberBox 4"]',
    luckyNumberBox4Text: '[data-testid="TextOnLuckyNumberBox 4"]',
  },

  multipliers: {
    bettingAreaMultiplier: '[data-testid="multiplier"]',
    luckyNumber0Multiplier: '[data-testid="multiplierOnLuckyNumberBox 0"]',
    luckyNumber1Multiplier: '[data-testid="multiplierOnLuckyNumberBox 1"]',
    luckyNumber2Multiplier: '[data-testid="multiplierOnLuckyNumberBox 2"]',
    luckyNumber3Multiplier: '[data-testid="multiplierOnLuckyNumberBox 3"]',
    luckyNumber4Multiplier: '[data-testid="multiplierOnLuckyNumberBox 4"]',
  }

};

export const TP2020Locators = {
  playerA: '[data-name="main-bet playera"]',
  playerAText: '[for="playerA"]',
  // playerAText: '//div[@data-name="main-bet playera"]/div/div/div/h2',
  playerB: '[data-name="main-bet playerb"]',
  playerBText: '[for="playerB"]',
  // playerBText: '//div[@data-name="main-bet playerb"]/div/div[2]/h2',
  playerAPairPlus: '[data-name="side-bet playera"]',
  playerAPairPlusText: '//div[@data-name="side-bet playera"]/div',
  playerBPairPlus: '[data-name="side-bet playerb"]',
  playerBPairPlusText: '//div[@data-name="side-bet playerb"]/div',
  threePlusThreeBonus: '[data-name="side-bet 3plus3Bonus"]',
  statisticsTitle: '#statisticTitle',
  statisticsPlayerA: '#statisticPlayera',
  statisticsPlayerB: '#statisticPlayerb',
  statisticsPairPlusA: '#statisticPairPlusa',
  statisticsPairPlusB: '#statisticPairPlusb',
  virtualPanelPlayerA: '#playerb',
  virtualPanelPlayerB: '#playera',
};

export const SBLocators = {
  small: '[data-name="small"]',
  big: '[data-name="big"]',
  anyTripple: '[data-name="anyTripple"]',
  bet111: '[data-name="bet111"]',
  bet222: '[data-name="bet222"]',
  bet333: '[data-name="bet333"]',
  bet444: '[data-name="bet444"]',
  bet555: '[data-name="bet555"]',
  bet666: '[data-name="bet666"]',
  bet11: '[data-name="bet1-1"]',
  bet22: '[data-name="bet2-2"]',
  bet33: '[data-name="bet3-3"]',
  bet44: '[data-name="bet4-4"]',
  bet55: '[data-name="bet5-5"]',
  bet66: '[data-name="bet6-6"]',
  betOne: '[data-name="betOne"]',
  betTwo: '[data-name="betTwo"]',
  betThree: '[data-name="betThree"]',
  betFour: '[data-name="betFour"]',
  betFive: '[data-name="betFive"]',
  betSix: '[data-name="betSix"]',
  bet4: '[data-name="bet4"]',
  bet5: '[data-name="bet5"]',
  bet6: '[data-name="bet6"]',
  bet7: '[data-name="bet7"]',
  bet8: '[data-name="bet8"]',
  bet9: '[data-name="bet9"]',
  bet10: '[data-name="bet10"]',
  betOneOne: '[data-name="bet11"]',
  betOneTwo: '[data-name="bet12"]',
  betOneThree: '[data-name="bet13"]',
  betOneFour: '[data-name="bet14"]',
  betOneFive: '[data-name="bet15"]',
  betOneSix: '[data-name="bet16"]',
  betOneSeven: '[data-name="bet17"]',
  bet1_2: '[data-name="bet1-2"]',
  bet1_3: '[data-name="bet1-3"]',
  bet1_4: '[data-name="bet1-4"]',
  bet1_5: '[data-name="bet1-5"]',
  bet1_6: '[data-name="bet1-6"]',
  bet2_3: '[data-name="bet2-3"]',
  bet2_4: '[data-name="bet2-4"]',
  bet2_5: '[data-name="bet2-5"]',
  bet2_6: '[data-name="bet2-6"]',
  bet3_4: '[data-name="bet3-4"]',
  bet3_5: '[data-name="bet3-5"]',
  bet3_6: '[data-name="bet3-6"]',
  bet4_5: '[data-name="bet4-5"]',
  bet4_6: '[data-name="bet4-6"]',
  bet5_6: '[data-name="bet5-6"]',
};

// export const TROLocators = {
//   zero: '[data-name="main-bet 0"]',
//   one: '[data-name="main-bet 1"]',
//   two: '[data-name="main-bet 2"]',
//   three: '[data-name="main-bet 3"]',
//   four: '[data-name="main-bet 4"]',
//   five: '[data-name="main-bet 5"]',
//   six: '[data-name="main-bet 6"]',
//   seven: '[data-name="main-bet 7"]',
//   eight: '[data-name="main-bet 8"]',
//   nine: '[data-name="main-bet 9"]',
//   ten: '[data-name="main-bet 10"]',
//   eleven: '[data-name="main-bet 11"]',
//   twelve: '[data-name="main-bet 12"]',
//   thirteen: '[data-name="main-bet 13"]',
//   fourteen: '[data-name="main-bet 14"]',
//   fifteen: '[data-name="main-bet 15"]',
//   sixteen: '[data-name="main-bet 16"]',
//   seventeen: '[data-name="main-bet 17"]',
//   eighteen: '[data-name="main-bet 18"]',
//   nineteen: '[data-name="main-bet 19"]',
//   twenty: '[data-name="main-bet 20"]',
//   twentyone: '[data-name="main-bet 21"]',
//   twentytwo: '[data-name="main-bet 22"]',
//   twentythree: '[data-name="main-bet 23"]',
//   twentyfour: '[data-name="main-bet 24"]',
//   twentyfive: '[data-name="main-bet 25"]',
//   twentysix: '[data-name="main-bet 26"]',
//   twentyseven: '[data-name="main-bet 27"]',
//   twentyeight: '[data-name="main-bet 28"]',
//   twentynine: '[data-name="main-bet 29"]',
//   thirty: '[data-name="main-bet 30"]',
//   thirtyone: '[data-name="main-bet 31"]',
//   thirtytwo: '[data-name="main-bet 32"]',
//   thirtythree: '[data-name="main-bet 33"]',
//   thirtyfour: '[data-name="main-bet 34"]',
//   thirtyfive: '[data-name="main-bet 35"]',
//   thirtysix: '[data-name="main-bet 36"]',
//   first12: '[data-name="side-bet 1st 12"]',
//   second12: '[data-name="side-bet 2nd 12"]',
//   third12: '[data-name="side-bet 3rd 12"]',
//   oneto18: '[data-name="side-bet 1-18"]',
//   nineteento36: '[data-name="side-bet 19-36"]',
//   even: '[data-name="side-bet EVEN"]',
//   odd: '[data-name="side-bet ODD"]',
//   red: '[data-name="side-bet red"]',
//   black: '[data-name="side-bet black"]',
//   twoto1150: '[data-name="side-bet 2 to 1 150 "]',
//   twoto1149: '[data-name="side-bet 2 to 1 149 "]',
//   twoto1148: '[data-name="side-bet 2 to 1 148 "]',
// };

export const TTCLocators = {
  player8Bet: '[data-name="main-bet player8bet"]',
  player8BetChip: '[data-testid="main-bet-chip player8bet"]',
  player8Lay: '[data-name="side-bet player8lay"]',
  player8LayChip: '[data-testid="side-bet-chip player8lay"]',
  player8Text: '#player8',
  player9Bet: '[data-name="main-bet player9bet"]',
  player9BetChip: '[data-testid="main-bet-chip player9bet"]',
  player9Lay: '[data-name="side-bet player9lay"]',
  player9LayChip: '[data-testid="side-bet-chip player9lay"]',
  player9Text: '#player9',
  player10Bet: '[data-name="main-bet player10bet"]',
  player10BetChip: '[data-testid="main-bet-chip player10bet"]',
  player10Lay: '[data-name="side-bet player10lay"]',
  player10LayChip: '[data-testid="side-bet-chip player10lay"]',
  player10Text: '#player10',
  player11Bet: '[data-name="main-bet player11bet"]',
  player11BetChip: '[data-testid="main-bet-chip player9bet"]',
  player11Lay: '[data-name="side-bet player11lay"]',
  player11LayChip: '[data-testid="side-bet-chip player11lay"]',
  player11Text: '#player11',
  lastCard: 'svg[class="card card-spades-9"]',
  secondCard: 'svg[class="card card-diamonds-7"]',
  specificCardforSumText: 'svg[class="card card-spades-8"]',

  virtualCardsHolderPlayer8: '[data-testid="virtualCardsHolderPlayer8"]',
  displayedCardInPlayer8VirtualHolder: 'svg[class="card card-hearts-6"]',
  virtualCardsHolderPlayer9: '[data-testid="virtualCardsHolderPlayer9"]',
  displayedCardInPlayer9VirtualHolder: 'svg[class="card card-diamonds-7"]',
  virtualCardsHolderPlayer10: '[data-testid="virtualCardsHolderPlayer10"]',
  displayedCardInPlayer10VirtualHolder: 'svg[class="card card-spades-8"]',
  virtualCardsHolderPlayer11: '[data-testid="virtualCardsHolderPlayer11"]',
  displayedCardInPlayer11VirtualHolder: 'svg[class="card card-clubs-9"]',
  noCardsPresentInPlayersVirtualHolders: 'svg[class="card card-undefined-undefined"]',


  totalPointsPlayerEight: '[data-testid="totalPointsPlayer8"]',
  totalPointsPlayerNine: '[data-testid="totalPointsPlayer9"]',
  totalPointsPlayerTen: '[data-testid="totalPointsPlayer10"]',
  totalPointsPlayerEleven: '[data-testid="totalPointsPlayer11"]',
  eightPlusText: '[data-testid="8PlusText"]',
  ninePlusText: '[data-testid="9PlusText"]',
  tenPlusText: '[data-testid="10PlusText"]',
  elevenPlusText: '[data-testid="11PlusText"]',
  playerEightLabel: '[data-testid="player8Label"]',
  playerNineLabel: '[data-testid="player9Label"]',
  playerTenLabel: '[data-testid="player10Label"]',
  playerElevenLabel: '[data-testid="player11Label"]',

  virtualBox: '[data-testid="virtualBox"]',
  virtualBoxPlayerEight: '[data-testid="virtualBoxPlayerEight"]',
  virtualBoxPlayerNine: '[data-testid="virtualBoxPlayerNine"]',
  virtualBoxPlayerTen: '[data-testid="virtualBoxPlayerTen"]',
  virtualBoxPlayerEleven: '[data-testid="virtualBoxPlayerEleven"]',

  statisticsBtn: '[data-testid="statisticsBtn"]',
  statisticsTab: '[data-testid="statisticsTab"]',
  statisticsTitle: '[data-testid="statisticsTitle"]',
  statisticsTitleIcon: '[data-testid="statisticsTitleIcon"]',
  statisticsTable: '[data-testid="statisticsTable"]',
  statisticsTableFirstItem: '[data-testid="statisticsTableFirstItem"]',
  statisticsDiagram: '[data-testid="statisticsDiagram"]',
  statisticsDiagramPlayerEight: '[data-testid="statisticsDiagramPlayerEight"]',
  statisticsDiagramPlayerNine: '[data-testid="statisticsDiagramPlayerNine"]',
  statisticsDiagramPlayerTen: '[data-testid="statisticsDiagramPlayerTen"]',
  statisticsDiagramPlayerEleven: '[data-testid="statisticsDiagramPlayerEleven"]',
  statisticsLastRounds: '[data-testid="statisticsLastRounds"]'
};

export const UBJLocators = {
  mainBetspot: '[data-name="main-bet"]',
  mainBetspotChip: '[data-testid="main-bet-chip"]',
  twentyonePlusThree: '[data-name="21+3"]',
  twentyonePlusThreeBetspotChip: '[data-testid="side-bet-chip twentyOnePlusThree"]',
  bustIt: '[data-name="bust it"]',
  bustItBetspotChip: '[data-testid="side-bet-chip bustIt"]',
  hot3: '[data-name="hot 3"]',
  hot3BetspotChip: '[data-testid="side-bet-chip hotThree"]',
  anyPair: '[data-name="any pair"]',
  anyPairBetspotChip: '[data-testid="side-bet-chip anyPair"]',

  allSideBets: '[data-name="all side bets"]', // to be implemented in game, not working now
  sideBetsPanel: '[data-testid="sideBetsPanel"]',
  sideBetsPopUp: '[data-testid="sideBetsPopUp"]',
  closeSideBetsPopUpBtn: '[data-testid="side-bets-close-button"]',
  playerCounter: '[data-testid="playerCounter"]',

  decisionHitBtn: '[data-testid="decision-hit"]',
  decisionStandBtn: '[data-testid="decision-stand"]',
  decisionSplitBtn: '[data-testid="decision-split"]',
  decisionDoubleDownBtn: '[data-testid="decision-doubleDown"]',
  decisionFoldBtn: '[data-testid="decision-fold"]',
  blackJackPlayerCardsIcon: 'svg[name="blackJack"]',

  insuranceText: '[data-testid="insuranceText"]',
  insuranceYesBtn: '.icon-insuranceYes',
  insuranceYesText: '[data-testid="decisionYesText"]',
  insuranceNoBtn: '[data-testid="decisionNo"]',
  insuranceNoText: '[data-testid="decisionNoText"]',
  insuranceIcon: '[data-testid="iconInsurance"]',

  evenMoneyText: '[data-testid="evenMoneyText"]',
  evenMoneyYesBtn: '.icon-evenMoneyYes',
  evenMoneyYesText: '[data-testid="decisionYesText"]',
  evenMoneyNoBtn: '[data-testid="decisionNo"]',
  evenMoneyNoText: '[data-testid="decisionNoText"]',
  evenMoneyIcon: '[data-testid="iconEvenMoney"]',

  dealerCardsSum: '[data-testid="dealerCardsSum"]',
  playerCardsSum: '[data-testid="playerCardsSum"]',

};

export const UPLocators = {
  ante: '[data-name="main-bet ante"]',
  blind: '',
  trips: '[data-name="side-bet trips"]',
};