import { GamesNamesEnum } from './gameNames.enum.ts' ;


export enum CardIdEnum {
  ACE_OF_DIAMONDS = 1,
  TWO_OF_DIAMONDS = 2,
  THREE_OF_DIAMONDS = 3,
  FOUR_OF_DIAMONDS = 4,
  FIVE_OF_DIAMONDS = 5,
  SIX_OF_DIAMONDS = 6,
  SEVEN_OF_DIAMONDS = 7,
  EIGHT_OF_DIAMONDS = 8,
  NINE_OF_DIAMONDS = 9,
  TEN_OF_DIAMONDS = 10,
  JACK_OF_DIAMONDS = 11,
  QUEEN_OF_DIAMONDS = 12,
  KING_OF_DIAMONDS = 13,
  ACE_OF_SPADES = 14,
  TWO_OF_SPADES = 15,
  THREE_OF_SPADES = 16,
  FOUR_OF_SPADES = 17,
  FIVE_OF_SPADES = 18,
  SIX_OF_SPADES = 19,
  SEVEN_OF_SPADES = 20,
  EIGHT_OF_SPADES = 21,
  NINE_OF_SPADES = 22,
  TEN_OF_SPADES = 23,
  JACK_OF_SPADES = 24,
  QUEEN_OF_SPADES = 25,
  KING_OF_SPADES = 26,
  ACE_OF_HEARTS = 27,
  TWO_OF_HEARTS = 28,
  THREE_OF_HEARTS = 29,
  FOUR_OF_HEARTS = 30,
  FIVE_OF_HEARTS = 31,
  SIX_OF_HEARTS = 32,
  SEVEN_OF_HEARTS = 33,
  EIGHT_OF_HEARTS = 34,
  NINE_OF_HEARTS = 35,
  TEN_OF_HEARTS = 36,
  JACK_OF_HEARTS = 37,
  QUEEN_OF_HEARTS = 38,
  KING_OF_HEARTS = 39,
  ACE_OF_CLUBS = 40,
  TWO_OF_CLUBS = 41,
  THREE_OF_CLUBS = 42,
  FOUR_OF_CLUBS = 43,
  FIVE_OF_CLUBS = 44,
  SIX_OF_CLUBS = 45,
  SEVEN_OF_CLUBS = 46,
  EIGHT_OF_CLUBS = 47,
  NINE_OF_CLUBS = 48,
  TEN_OF_CLUBS = 49,
  JACK_OF_CLUBS = 50,
  QUEEN_OF_CLUBS = 51,
  KING_OF_CLUBS = 52,
  // getPropertyFromValue = (v) => Object.keys(cardId).find((x) => cardId[x] === v),
}
export const getCardNameFromCardId = (v: number): string | undefined => {
  const result = Object.keys(CardIdEnum).find((x) => CardIdEnum[x] === v);
  return result as string | undefined;
};


  export const emptyCardMap: Record<GamesNamesEnum, CardIdEnum[]> = {
  [GamesNamesEnum.BJ]: [],
  [GamesNamesEnum.RO]: [],
  [GamesNamesEnum.TRO]: [],
  [GamesNamesEnum.DRO]: [],
  [GamesNamesEnum.UBJ]: [],
  [GamesNamesEnum.BAC]: [],
  [GamesNamesEnum.DT]: [],
  [GamesNamesEnum.SB]: [],
  [GamesNamesEnum.AB]: [],
  [GamesNamesEnum.TP]: [],
  [GamesNamesEnum.TP2020]: [],
  [GamesNamesEnum.TTC]: [],
  [GamesNamesEnum.UP]: [],
};

